name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -S -p 453921 -a qv63EkGb
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
