name: Curse Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Add fallback toc
      run: cp Journalator_Mainline.toc Journalator.toc
    - uses: BigWigsMods/packager@v2
      with:
        args: -p 453921 -a qv63EkGb
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
